apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
data:
  # This is "MySuperSecurePassword123!" encoded in Base64
  # To encode your own: echo -n "YOUR_PASSWORD" | base64
  DB_PASSWORD: "TXlTdXBlclNlY3VyZVBhc3N3b3JkMTIzIQ=="