- name: Deploy Micro-Blog to AKS
  hosts: localhost         # Run this on the GitHub runner itself
  connection: local
  
  tasks:
    - name: Log in to Azure (handled by GitHub Action)
      debug:
        msg: "Azure login is assumed to be done by the azure/login@v1 GitHub Action."
        
    - name: Get AKS cluster credentials
      # This command logs 'kubectl' into your AKS cluster
      command: az aks get-credentials --resource-group {{ lookup('env', 'AZURE_RG_NAME') }} --name {{ lookup('env', 'AZURE_AKS_NAME') }} --overwrite-existing
      
    - name: Deploy Kubernetes manifests
      # This is the magic step. It applies all your .yaml files.
      kubernetes.core.k8s:
        state: present
        src: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/k8s/{{ item }}"
        namespace: default
      loop:
        - 00-secrets.yaml
        - 01-posts-service.yaml
        # - 02-comments-service.yaml (uncomment when ready)
        # - 03-auth-service.yaml (uncomment when ready)
        - 04-frontend.yaml
        - 05-ingress.yaml