- name: Deploy Micro-Blog to AKS
  hosts: localhost
  connection: local
  
  tasks:
    - name: Log in to Azure (handled by GitHub Action)
      debug:
        msg: "Azure login is assumed to be done."

    # --- ADD THIS NEW TASK ---
    - name: Install Nginx Ingress Controller
      command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
      changed_when: false # This command always reports 'changed', so we override it
    # --- END NEW TASK ---
        
    - name: Get AKS cluster credentials
      command: az aks get-credentials --resource-group {{ lookup('env', 'AZURE_RG_NAME') }} --name {{ lookup('env', 'AZURE_AKS_NAME') }} --overwrite-existing
      
    - name: Deploy Kubernetes manifests
      kubernetes.core.k8s:
        state: present
        src: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/k8s/{{ item }}"
        namespace: default
      loop:
        - 00-secrets.yaml
        - 01-posts-service.yaml
        - 04-frontend.yaml
        - 05-ingress.yaml