name: Build and Deploy Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_RG_NAME: "myblog-rg" 
  AZURE_AKS_NAME: "myblog-aks"
  AZURE_ACR_NAME: "myblogacr98756jibin.azurecr.io"

jobs:
  # JOB 1: Build and Push Images
  build_and_push_docker:
    name: 1. Build and Push Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_ACR_NAME }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          
      - name: Build and push posts-service
        run: |
          docker build -t ${{ env.AZURE_ACR_NAME }}/posts-service:latest ./services/posts-service
          docker push ${{ env.AZURE_ACR_NAME }}/posts-service:latest
          
      - name: Build and push frontend
        run: |
          docker build -t ${{ env.AZURE_ACR_NAME }}/frontend:latest ./services/frontend
          docker push ${{ env.AZURE_ACR_NAME }}/frontend:latest

  # JOB 2: Deploy to AKS
  deploy_to_aks:
    name: 2. Deploy to AKS
    runs-on: ubuntu-latest
    needs: [build_and_push_docker] # This now waits ONLY for the build
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Ansible and K8s tools
        run: |
          pip install ansible
          pip install kubernetes
          ansible-galaxy collection install azure.azcollection
          
      # This is the only step needed to run the deployment.
      # Your Ansible playbook handles getting credentials,
      # installing ingress, waiting, and deploying.
      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml